server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

greeting:
  message:  webhoxxxxxxxxxxxxxxxaaay!!

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.*: DEBUG
