server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

greeting:
  message:  webhook worked yaaay!!

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

