eureka:
  client: 
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
        routes:
        - id: hello-server
          uri: lb://hello-server
          predicates:
          - Path=/s1/**
          filters:
          - RewritePath=/s1/(?<path>.*), /$\{path}
          - RedirectTo=302, https://spring.io

# security:
#   oauth2:
#     resource:
#       userInfoUri: http://localhost:8901/auth/user
