eureka:
  instance:
    preferIpAddress: true
  client: 
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
      - id: hello-server
        uri: lb://hello-server

        predicates:
        - Path=/s1/**

        filters: 
        - RewritePath=/s1/
                    (?<path>.*),/$\{path}

          

management:
  endpoints:
    web:
      exposure:
        include: "*"

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8901/auth/user
